################################################################################
[version]
name = "Bump Version"
description = "Bump the version number to the next /patch/ level and commit locally"

  [[version.steps]]
  method = "poetry_bump_version_patch"
  confirm = true

  [[version.steps]]
  method = "update_readme"
  confirm = true

  [[version.steps]]
  method = "git_commit_version_files"
  confirm = true

################################################################################
[build]
name = "Build"
description = "Build our distribution(s)."

  [[build.steps]]
  method = "build"
  echo_stdout = true

################################################################################
[clean]
name = "Clean"
description = "Clean out our temp files and ALL previous builds."

  [[clean.steps]]
  method = "clean"
  confirm = true
