################################################################################
[[recipes]]
id_="version"
name = "Bump Version"
description = "Bump the version number to the next /patch/ level and commit locally"

[[recipes.steps]]
method = "poetry_bump_version_patch"

[[recipes.steps]]
method = "update_readme"

[[recipes.steps]]
method = "git_commit_version_files"

################################################################################
[[recipes]]
id_="build"
name = "Build"
description = "Build our distribution(s)."

[[recipes.steps]]
method = "build"
confirm = false
echo_stdout = true

################################################################################
[[recipes]]
id_="clean"
name = "Clean"
description = "Clean out our temp files and ALL previous builds."

[[recipes.steps]]
method = "clean"
