################################################################################
[recipes.version]
name = "Bump Version"
description = "Bump the version number to the next /patch/ level and commit locally"

[[recipes.version.steps]]
method = "poetry_bump_version_patch"

[[recipes.version.steps]]
method = "update_readme"

[[recipes.version.steps]]
method = "git_commit_version_files"

################################################################################
[recipes.build]
name = "Build"
description = "Build our distribution(s)."

[[recipes.build.steps]]
method = "build"
confirm = false
echo_stdout = true

################################################################################
[recipes.clean]
name = "Clean"
description = "Clean out our temp files and ALL previous builds."

[[recipes.clean.steps]]
method = "clean"
