################################################################################
[[recipes]]
name = "bump"
description = "Bump the version number to the next /patch/ level and commit locally"

[[recipes.steps]]
action = "poetry_bump_version_patch"

[[recipes.steps]]
action = "update_readme"

[[recipes.steps]]
action = "git_commit_version_files"

################################################################################
[[recipes]]
name = "build"
description = "Build our distribution(s)."

[[recipes.steps]]
action = "build"
confirm = false
echo_stdout = true

################################################################################
[[recipes]]
name = "clean"
description = "Clean out our temp files and ALL previous builds."

[[recipes.steps]]
action = "clean"
