* Manage
  Inspired immensely by [[https://github.com/tfeldmann/organize/blob/main/manage.py][Thomas Feldman's manage.py]] script in his [[https://github.com/tfeldmann/organize][Organize]] project, this package automates several common operations for poetry & org-based package management, particularly those that I don't perform regularly and/or require multiple steps to perform (and thus, tend to forget how to do them!)
** Approach
   - The exact steps necessary to achieve a /target/ are specified in a local ~manage.yaml~ file that is specific to your project.
   - Plugins will be possible by adding operations to the ~manage/commands~ directory (they'll be picked up automatically).
** Assumptions
*** Tools
    - [[https://python-poetry.org][Poetry]] is used manage our package dependencies *and* build environment.
    - We assume that execution of this script is from the TOP level of a project, i.e. at the same level as pyproject.toml.
    - The version string in pyproject.toml is the SINGLE and CANONICAL version string in our project/package.
*** Versioning
    - We use semantic versioning with ~poetry version~ to update/manage our version number.
*** README Management
    - We manage our README in an Org format (see [[https://orgmode.org/][Emacs Org Mode]] for details).
    - We assume ~README.org~ is kept in the top-level directory.
*** CHANGELOG Management
    - We do *not* use a stand-alone ~CHANGELOG.md~ file.
    - We use a specific section in ~README.org~ called /Release History/.
    - We keep a list of completed but unreleased items in the /Release History/ under an "Unreleased" header.
*** Configuration
    - We need *two* --group dev packages over and above our default environment to support this script tomli and requests.
    - We assume the following entries are available in our environment (either set in shell or through .env):
     |--------------------------------+-------------------------------------------+--------------------------------------------------------------------------|
     | GITHUB_USER                    | Github user id                            | JohnJacobJingleheimerSchmidt                                             |
     | GITHUB_API_TOKEN               | Github personal API token                 | ghp_1234567890ABCDEFG1234567890                                          |
     | GITHUB_API_RELEASES            | URL to Github release API                 | https://api.github.com/repos/<user>/<project>/releases                   |
     | GITHUB_PROJECT_RELEASE_HISTORY | URL to release history (for release body) | https://github.com/<user>/<project/blob/trunk/README.org#release-history |
     |--------------------------------+-------------------------------------------+--------------------------------------------------------------------------|
** GTD
   - Add a command-line parameter to take a specific poetry version "bump", ie /major/ and /minor/ over and above our current /patch/.
   - Convert configuration over to pydantic for validation and documentation.
   - Add a command-line parameter to point to a specific manage recipe file (instead of default manage.toml)
   - Add a command-line parameter for verbosity (-v, -vv, -vvv?)
     - -v:
       - print absolute paths associated with readme and pyproject.
       - print package name and version found, how many recipes encountered etc.
     - -vv:
       - add explicit output of commands, e.g. how many recipes
   - Add tests!
** Release History
*** Unreleased
*** v0.0.10 - 2023-01-26
    - ADDED: A "check" recipe target to simply run the setup & validation steps only.
    - ADDED: A validation that the version in ~pyproject.toml~ is consistent with the last release in the Release History of ~README.org~.
    - CHANGED: Changed terminology from ~target~ to ~recipe~ and manage.toml to consisting of /recipes/.
    - CHANGED: Complete refactoring to make commands "granular" and dynamically loaded from ~commands~ module.
    - CHANGED: Convert over to TOML instead of YAML for configuration file.
*** v0.0.9 - 2023-01-25
    - CHANGED: Catch exception when manage.yaml can't be opened.
*** v0.0.8 - 2023-01-25
    - ADDED: Missing /bin/manage script for execution after pip/poetry install.
*** v0.0.7 - 2023-01-25
    - ADDED: Assumptions and example configurations to README.org.
*** v0.0.6 - 2023-01-25
*** v0.0.5 - 2023-01-25
*** v0.0.4 - 2023-01-25
*** v0.0.3 - 2023-01-25
*** v0.0.2 - 2023-01-25
    - Initial packaging.
