################################################################################
[[recipes]]
id_="version"
name = "Bump Version"
description = "Bump the version number a single patch level and commit locally"

[[recipes.steps]]
method = "poetry_bump_version_patch"

[[recipes.steps]]
method = "update_readme"

[[recipes.steps]]
method = "git_commit_version_files"


################################################################################
[[recipes]]
id_="build"
name = "Build"
description = "Build our distribution(s)."

[[recipes.steps]]
method = "run_pre_commit"
echo_stdout = true

[[recipes.steps]]
method = "clean"
allow_error = true
confirm = false

[[recipes.steps]]
method = "build"
echo_stdout = true
confirm = false


################################################################################
[[recipes]]
id_="publish"
name = "Publish to PyPI"
description = "Release a new version of our package to PyPI."

[[recipes.steps]]
method = "git_create_tag"

[[recipes.steps]]
method = "git_push_to_github"

[[recipes.steps]]
method = "publish_to_pypi"

[[recipes.steps]]
method = "git_create_release"
